usd-cs/COMP-491-24-25-Sustainability-Dashboard

backend/__tests__/loginUser.test.js
backend/babel.config.js
backend/database_connection.js
backend/jest.config.js
backend/package-lock.json
backend/package.json

Created tests for login functionality on backend using Jest

tests for loginuser pass on backend

---

backend/__tests__/loginUser.test.js
frontend/index.html
frontend/src/App.vue
frontend/src/components/LoginPage.vue
frontend/src/tests/AdminLoginPage.test.js
package-lock.json
package.json
vitest.backend.config.js
vitest.config.js
vitest.frontend.config.js

Created a vue login form page that John will be routed to on open. There is a weird overflow on the screen that I need help fixing. I added a vitest file to test the frontend and then also changed the backend test to also use vitest since its much more compatible with ES modules. All test pass with npm test and it tests the backend first and then the frontend.

added frontend login page and tests

---

.gitignore
vite.config.js

edited the git ignore, to add mandatory config file, for css to properly operate in the front end.

Add vite config file 

---

backend/setup/setup_user.js

Set up first user in the user table to be able to test logging in on the frontend

setup for first user to populate into the table to be able to login

---

backend/__tests__/uploadFile.test.js
backend/auth/authMiddleware.js
backend/auth/controller.js
backend/auth/queries.js
backend/auth/queryDebug.js
backend/index.js
backend/package-lock.json
backend/package.json
backend/setup/setup_user.js

Wrote docstrings for login functionality in the backend following team's format in other files. Created testfile for fileUpload function to check on error messages and appropriate responses if file is correctly uploaded.

Docstrings and backend testing for file upload

---

frontend/src/App.vue
frontend/src/components/LoginPage.vue
frontend/src/components/MainPage.vue
frontend/src/components/UploadData.vue
frontend/src/components/UploadSuccess.vue
package-lock.json
package.json

Edited the frontend to match USD official colors, added a logo that routes to the main USD page and cleaned up overall UI for Login Page, and UploadData page

Edited the frontend to match USD official colors + more

---

backend/Dockerfile.backend
backend/create_schema.js
backend/database_connection.js
backend/setup/setup_user.js
docker-compose.yml
frontend/Dockerfile.frontend

- Frontend and backend are held in two separate containers.
- A base image of Postgres is added to the project and instance of our database is held within it.
- All database connections now no longer reference local host but their individual containers before being forwarded to their original ports. This maintains modularity. 
- Sample users and database schema scripts are automatically added when building or restarting all containers.
- Reduced development environment complexity, now one line "docker-compose up --build" starts the entire application.

Docker containerization 

---

.github/workflows/node.js.yml
backend/Dockerfile.backend
docker-compose.yml
frontend/Dockerfile.frontend

Made changes for containers to be running Linux so that all containers can be more easily run on all platforms.
Made sure all dependencies are reinstalled inside each individual container.

Changes made for OS agnostic docker configuration

---

.dockerignore
backend/Dockerfile.backend
backend/auth/routes.js
backend/index.js
backend/tables/table_controller.js
backend/tables/table_queries.js
backend/tables/table_routes.js
frontend/Dockerfile.frontend
frontend/src/components/BarChart.vue
frontend/src/components/MainPage.vue
frontend/src/router/router.js
package-lock.json
package.json

**Type of Change:** Bug fix of New Feature
**Summary:**  Setting up new routes, controllers, and queries to access the data that is currently stored in our postgres database. Once data is queried, a basic barchart populates on the front page. This will be refined later. 
Just the incomplete bar chart populates on the home page. Further implementation will have the main page be 1 of 4 things showing on the landing home page. 
Updated the queries for the database to ensure that querying a table returns actual rows. 
none
none

Setting up backend routes and queries to database for visualizations

---

frontend/src/components/BarChart.vue
frontend/src/components/MainPage.vue
package-lock.json

**Type of Change:** :
New Feature
**Summary:** 
Implement and define starting page, which allows for a template for each of the visual components of the dashboard to sit in. The navigation bar, integrates predefined routes, and adds a hover effect to all button for better visual notification for the user. Integrated graph component into template and allows for clickable functionality to better view graph display.
Describe what changes were made to the UI/UX for this request. 
Changed navigation bar to add hover effect, placement, and orientation to dashboard template. The template added to the front page, redefining the previous space to have clear defined areas for visual display.
No …

Base page rework for visualization implementation.

---

frontend/src/tests/BubbleChart.test.js

**Type of Change:** TEST
**Summary:** Wrote tests for the front end page for bubble chart. Ensures that when not in full page, no legend shows, and when in full page, legend shows. 
_TODO: No changes made
No changes made
No changes made

Wrote frontend test for bubble chart

---

backend/create_schema.js

Updating PostgreSQL database schema
Updated the create_schema.js file so that it creates a new table called bloom_meta_data that prevents duplicate records with the same date when we are calling the Bloom API daily to ingest into our other tables. It also adds a last_modified column that records the time of the last successful API pull. Ideally, before the performing a call to pull data, check the meta data table to check for date and last modified timestamp. …

updated schema to add a meta data table for bloom api calls

---

backend/__tests__/autoDB_refresh.test.js
backend/__tests__/fetchApiData.test.js
package-lock.json

**Type of Change:** Bug fix
**Summary:** Altering jest testing to be vitest so that workflow can pass smoothly. 
N/A

Autodb testing

---

backend/__tests__/checkDatabase.test.js
backend/__tests__/uploadAthenaFile.test.js
backend/auth/upload/upload_controller.js
backend/auth/upload/upload_routes.js
backend/create_schema.js
backend/index.js
frontend/src/components/FileImport.vue
frontend/src/components/UploadData.vue
frontend/src/tests/UploadPortal.test.js

**Type of Change:**  New Feature
**Summary:**  I created a new method in upload_controller.js that effectively parsing an athena solar csv file that we can consistently expect from the user. The method creates a new endpoint in the routes called athena-upload. Using the code from the last work on the frontend, I integrated a user selecting athena as their choice of upload to be ingested into our postgres database. The file parses each of the time stamps at each site, and includes a summed total kWh for that timestamp, as well as a metadata created_at column. Unit testing included. 
No changes made
New table: athena_hourly_output that holds timestamp for each record as well as kWh data for each site and a summed total as well.

Uploading Athena file and storing in postgres

---

vite.config.js

**Type of Change:** Other
**Summary:** adding sustainability.dedyn.io to hosts allowed in our vite.config.js file so we are able to launch http://sustainability.dedyn.io:5173/
No changes made. 
No changes made. 
No changes made. 

adding to config file 

---

backend/create_schema.js

_TODO: Describe what changes were made to your data model for this request. This could include things such as new database tables added and …

added user id to athena table

---

docker-compose.yml
vite.config.js

_TODO: Describe what changes were made to your data model for this request. This could include things such as new database tables added and …

editing compose yaml file for ports

---

docker-compose.yml

_TODO: Describe what changes were made to your data model for this request. This could include things such as new database tables added and …

Digitalocean

---

docker-compose.yml

_TODO: Describe what changes were made to your data model for this request. This could include things such as new database tables added and …

Digitalocean changes to yaml file

---

frontend/src/components/BarChart.vue
frontend/src/components/BubbleChart.vue
frontend/src/components/MainPage.vue
frontend/src/components/PieChart.vue
frontend/src/tests/BubbleChart.test.js
frontend/src/tests/MainPage.test.js

Added a background to our main page, replaced the navigation bar moving it to the top of the page. created new pages for each of the new tabs.
Added a background to our main page, replaced the navigation bar moving it to the top of …

Rework of main landing page

---

frontend/src/components/Sources.vue
frontend/src/components/SourcesGraph.vue

**Summary:** _TODO: Briefly summarize the changes made in this pull request, including the rationale for the changes. 
Implemented a feature for a user to compare electricity output between buildings. 
The original graph the user generated by selecting a building card is used as the base. The user can then click the "compare" button beneath the graph which generates a drop down of all building names. Upon selection an additional line of a different color is plotted on the graph allowing the user to compare energy output between buildings. Allows for comparison of up to all buildings on one graph. Tooltip has been updated so that relevant information is displayed to the user …

Added feature to compare energy output of user selected buildings.

---

frontend/src/tests/Sources.test.js
frontend/src/tests/SourcesGraph.test.js
package-lock.json
package.json

**Type of Change:** _TODO:_ Pick one of the following: Bug fix 
**Summary:** _TODO: Addressed an issue impacting expected functionality during testing. Changes were made to ensure consistent behavior across relevant scenarios.
_TODO: Briefly describe what changes were made to your object-oriented design for this request. This include updates to class models (e.g. new classes or interfaces, updates to classes, etc.),
state models, and interaction models (i.e. how objects interact with each other.
Provide either a link to your updated model diagrams (class diagram, state diagram, sequence diagrams, etc.) or directly embed them here.

Correct sources

---

backend/tables/table_controller.js
backend/tables/table_queries.js
backend/tables/table_routes.js
frontend/src/components/FileImport.vue
frontend/src/components/MainPage.vue
frontend/src/components/UploadData.vue
frontend/src/components/UploadSuccess.vue
frontend/src/tests/UploadSuccess.test.js

**Type of Change:** _TODO:_ New Feature
**Summary:** _TODO: Pulls data from athena and bloom tables to display last uploaded date on select page

Lastuploaded stamp

---

backend/__tests__/checkDatabase.test.js
backend/__tests__/tableQueries.test.js
backend/tables/table_controller.js
backend/tables/table_queries.js
backend/tables/table_routes.js
frontend/src/components/BarChart.vue
frontend/src/components/BarChartExpand.vue
frontend/src/components/BubbleChart.vue
frontend/src/components/BubbleChartExpand.vue
frontend/src/components/LineChart.vue
frontend/src/components/LineChartExpand.vue
frontend/src/components/MainPage.vue
frontend/src/components/PieChart.vue
frontend/src/components/PieChartExpand.vue
frontend/src/router/router.js
frontend/src/tests/BarChart.test.js
frontend/src/tests/BarChartExpand.test.js
frontend/src/tests/BubbleChart.test.js
frontend/src/tests/BubbleChartExpand.test.js
frontend/src/tests/LineChart.test.js
frontend/src/tests/LineChartExpand.test.js
frontend/src/tests/PieChart.test.js
frontend/src/tests/PieChartExpand.test.js

**Type of Change:**  New Features
**Summary:**  
updated bar chart, scatter plot, and pie chart to accuretly reflect the data. also updated the line chart as well. shifted everything up a bit on the main page so you can see that there is another componenet below the 4 boxes. did unit testing for everything
go click around the graphs and expand the accordions

Chart updates

---

frontend/src/components/SourcesGraph.vue
frontend/src/tests/SourcesGraph.test.js

**Summary:** 
- Corrected bug where duplicate timestamps were being added to x axis after selecting a new building.
- Added function where user can select and deselect buildings. To include visual identifier of current building selections in dropdown.
- Adjusted timestamp labels to read chronologically from starting from 12am and corrected plot points to match the labels.
- Added close button to match other graphs.
- Adjusted tests to reflect changes to component.

Hotfix sources charts

---

frontend/src/components/Sources.vue
frontend/src/tests/Sources.test.js

**Type of Change:** _TODO:_ Fixed sizing of sources page
**Summary:** 

Sources reformat

---

frontend/src/components/BarChart.vue
frontend/src/components/BaseFooter.vue
frontend/src/components/LineChart.vue
frontend/src/components/LineChartExpand.vue
frontend/src/components/MainPage.vue
frontend/src/components/NavBar.vue
frontend/src/components/PieChartExpand.vue
frontend/src/components/Sources.vue
frontend/src/components/SourcesGraph.vue

**Type of Change:** _TODO:_ Pick one of the following: Other
**Summary:** _TODO: Reformatting charts and pages in order to account for smaller screens. Added accordion for additional stored information about kwh

Accordion kwh

---

frontend/src/tests/Initiatives.test.js

Quick add of test file for initiative component.

Added test for init tab

---

backend/__tests__/loginUser.test.js
backend/auth/authMiddleware.js
backend/auth/controller.js
backend/auth/queries.js
backend/auth/queryDebug.js
backend/auth/upload/upload_routes.js
backend/create_schema.js
backend/database_connection.js
backend/setup/setup_user.js
frontend/src/components/LoginPage.vue
frontend/src/components/NavBar.vue
frontend/src/components/UploadData.vue
frontend/src/router/router.js
frontend/src/tests/AdminLoginPage.test.js
frontend/src/tests/UploadPortal.test.js

- Removed all default credentials, supported by environment variables.
- User login uses a username instead of email
- Added functionality for JWT token to be created upon user login, stored in local storage in front end
- Created protected routes that can only be used by an authenticated user
- Created middleware for protected routes to verify jwt token from frontend
- Added vue route guards to restrict access to admin pages
- upload page now sends JWT in header to be verified by backend before upload attempt
- logout now clears your JWT as well as redirected back to main

Security enhancement for unauthorized access.

---

cypress.config.js
frontend/src/components/BaseFooter.vue
frontend/src/components/LineChart.vue
frontend/src/components/Sources.vue
frontend/src/components/UploadSuccess.vue
frontend/src/tests/AdminLoginPage.test.js
frontend/src/tests/BubbleChartExpand.test.js
frontend/src/tests/LineChart.test.js
frontend/src/tests/SourcesGraph.test.js

Removed unused code throughout project to clear linter warnings

Clearing linter warnings. 
